POST    http://localhost:3001/api/persons
Content-Type: application/json
//There's gotta be a line break here and not between the URL and the Content-Type

{
    "name": "VS Code Test",
    "number": "123456"
}