POST    http://localhost:3001/api/notes
Content-Type: application/json
//There's gotta be a line break here and not between the URL and the Content-Type

{
    "content": "Last note!",
    "important": true,
    "userId": "63cb99df8fa7540c6dacb2fe"
}