POST    http://localhost:3003/api/blogs
Content-Type: application/json
//There's gotta be a line break here and not between the URL and the Content-Type

{
    "title": "Now with a user creator 444",
    "author": "Pepe Argento444",
    "url": "pepeargento.net444",
    "likes": 444
}