POST    http://localhost:3003/api/blogs
Content-Type: application/json
//There's gotta be a line break here and not between the URL and the Content-Type

{
    "title": "NEW BLOG SAM SMITH",
    "author": "SAMOTHY SMITHSON",
    "url": "samssmithawesomewebsiteforthewholefamily.net",
    "likes": 1000
}