POST    http://localhost:3003/api/blogs
Content-Type: application/json
//There's gotta be a line break here and not between the URL and the Content-Type

{
    "title": "SAM SMITH",
    "author": "123",
    "url": "123",
    "likes": 123
}